### PR TITLE
s/atom-shell/electron in ./tasks

### PR DESCRIPTION
**Pull request by thedaniel**
Not sure if this is sufficient, did it quick and dirty because there's breakage after renaming the repos.

### CODE REVIEW

**Comment by ioquatix** [comment]
Can we please get this fixed? I'm stuck trying to upgrade atom :(

**Comment by JordiOrlando** [comment]
Any tips on a workaround if this doesn't get merged soon?

**Comment by mgryszko** [comment]
I did the same change in order to download `electron` and it works.

**Comment by donspaulding** [comment]
I'm sure you don't need a whole pile of +1s, but in case it's not reported elsewhere, this is breaking the install of the entire atom-editor package from Arch Linux's User Repository.

**Comment by ioquatix** [comment]
Hey guys, I found a quick fix for arch users

```
pacman -R atom-editor
yaourt -S atom-editor-bin
```

Worked for me just fine.

**Comment by Jonahss** [comment]
It be nice if this of #24 got merged.
Atom build script is broken without this.

**Comment by Jonahss** [comment]
How about just publishing a new repo: grunt-download-electron

**Comment by as-cii** [comment]
:clap: :clap: :clap: 

@thedaniel: thanks for fixing this! Looks good to me, but I think we should rename the file as well.

There shouldn't be any further work to do here, therefore :shipit: after renaming!

:fireworks: :fireworks: :fireworks:

**Pull request merged**
